### ISSUE TITLE
Test cases failed with EI 6.2.0

### ISSUE THREAD

**Issue by Nirthika** [wso2-extensions/esb-connector-facebook#5]
**Description:**
11 Tests are failing with
ERROR - Axis2Sender Unexpected error during sending message out

Other than that 17 tests are failing: 

testCreateAttendingRSVPWithMandatoryParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): expected:<true> but was:<false>
  testCreateDeclinedRSVPWithMandatoryParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): expected:<true> but was:<false>
  testCreateMaybeRSVPWithMandatoryParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): expected:<true> but was:<false>
  testGetFriendListDetailsMandatoryParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): JSONObject["id"] not found.
  testCreateLikeWithMandatoryParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): expected:<true> but was:<false>
  testUploadPhotoMandatoryParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): JSONObject["id"] not found.
  testUploadVideoMandatoryParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): JSONObject["id"] not found.
  testCreateAppAchievementsWithMandatoryParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): JSONObject["success"] not found.
  testPublishNotificationWithMandatoryParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): JSONObject["success"] not found.
  testAddPageVideoMandatoryParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): expected:<true> but was:<false>
  testAddPhotoToPageMandatoryParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): JSONObject["id"] not found.
  testGetGroupDetailsWithMandatoryParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): JSONObject["id"] not found.
  testGetGroupDetailsWithOptionalParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): JSONObject["id"] not found.
  testGetMessageWithMandatoryParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): JSONObject["id"] not found.
  testGetMessageWithOptionalParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): JSONObject["from"] not found.
  testUpdatePagePictureMandatoryParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): expected:<true> but was:<false>
  testReplyToConversationWithMandatoryParameters(org.wso2.carbon.connector.integration.test.facebook.FacebookConnectorIntegrationTest): JSONObject["id"] not found.

**Comment by anupama-pathirage** [comment]
Closing this issue as this is in EI older version
